version: '3.8'
services:
  currency-app:
    build: .
    container_name: currency-app
    ports:
      - "8081:8081"
    environment:
      - API_EXCHANGERATE_KEY=${API_EXCHANGERATE_KEY}
    restart: always