spring.application.name=currencyservice
# Test commit to verify VS Code connection
server.port=8081

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# External API Config
api.exchangerate.key=0ebe82e0216e065b303a8a03
api.exchangerate.url=https://v6.exchangerate-api.com/v6/

# Enable the H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL queries in the terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace

# Swagger UI configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs